### ISSUE TITLE
How to add other kinds of Tradfri devices?

### ISSUE THREAD

**Issue by rei-vilo** [tim-hellhake/tradfri-adapter#2]
The bulb works fine after three tentatives.

How to add other kinds of Tradfri devices, like the [remote-controlled plug](https://www.ikea.com/gb/en/p/tradfri-wireless-control-outlet-00364477/)?

![tradfri-wireless-control-outlet__0515596_PE640308_S5](https://user-images.githubusercontent.com/951776/73463588-ce56f600-437d-11ea-9ac6-506d3dfd8f9e.JPG)

**Comment by tim-hellhake** [comment]
Thanks to @grifdail the power adapter should be supported now.
Can you please check it after updating to version 0.2.0 of the adapter?

**Comment by rei-vilo** [comment]
It works great, thank you!

<img width="1278" alt="Capture d’écran 2020-02-24 à 14 28 36" src="https://user-images.githubusercontent.com/951776/75156272-0b5ea000-5712-11ea-9945-3c25c957b458.png">
