### ISSUE TITLE
Devices "TRADFRI driver" and "Ropudden" are not dimmable.

### ISSUE THREAD

**Issue by Knaifhogg** [tim-hellhake/tradfri-adapter#8]
In the IKEA app you can dim Trådfri driver and Ropudden (light bulb), however in this addon you can only toggle them on and off.

**Comment by tim-hellhake** [comment]
Thanks for the note!
The adapter adds the properties depending on which spectrum is reported by the client library.
I added the info to the log so we can see what the library is reporting in your case.
Unfortunately, I don't have the driver, so you have to check the logs for me.

**Comment by tim-hellhake** [comment]
@Knaifhogg Did you have a chance to check the logs?

**Comment by Knaifhogg** [comment]
@tim-hellhake I had to reinstall my system but I did it right now. The logs are from a fresh install where I install and configure the addon, scan for devices, then toggle the devices found to show they work. [run-app_log.txt](https://github.com/tim-hellhake/tradfri-adapter/files/4972814/run-app_log.txt)
Unrelated to this specific issue is that the motion sensor and remote control are detected as well but not handled.

**Comment by tim-hellhake** [comment]
Seems like basic lights had no dimmer property until now.
With the next update, you should be able to dim them.

**Comment by tim-hellhake** [comment]
I also added support for remotes.
But the only thing they report is their battery level.

**Comment by tim-hellhake** [comment]
I added general battery level support for all battery-powered devices.

**Comment by tim-hellhake** [comment]
According to the comments in the code, the motion sensor is not supported.
We can still try it though.
Maybe it's recognized as a `sensor accessory`.
I added some additional logs for that.

**Comment by Knaifhogg** [comment]
@tim-hellhake If you provide a way for me to run 0.3.0, I can get you another log. I am too new to know how to change version by myself and compile it.

**Comment by tim-hellhake** [comment]
Don't worry.
I already prepared a new release.
As soon as the referenced PR is merged, you can install the new update in your gateway.

**Comment by tim-hellhake** [comment]
@Knaifhogg Is everything working?

**Comment by Knaifhogg** [comment]
@tim-hellhake Yes, It works as expected now. Good job.
