### ISSUE TITLE
Cannot find Tradfri bridge

### ISSUE THREAD

**Issue by davvore33** [tim-hellhake/tradfri-adapter#9]
Hi,
your plugin looks very interesting, since my firewall has some specific rules probably adapter is not able to find my bridge,
so I'd like to have a way to manually insert the IP of my bridge

**Comment by tim-hellhake** [comment]
I'm sorry to hear that.
If it's possible, I will add it as an option, but I need to check first if the underlying library supports it.

**Comment by tim-hellhake** [comment]
Ok looks fine.
I'm not sure if I'm able to fix it today, though.
Would you mind still adding the logs after restarting the adapter?
You can see them on `/settings/developer/.
I wonder if your device is not discovered at all or the name resolution doesn't work.

**Comment by tim-hellhake** [comment]
Ok, looks fine.
I'm not sure if I'm able to fix it today, though.
Would you mind still adding the logs after restarting the adapter?
You can see them on `/settings/developer/`.
I wonder if your device is not discovered at all, or the name resolution doesn't work.

**Comment by davvore33** [comment]
wow thanks for your fast action, I'll try it ASAP

**Comment by tim-hellhake** [comment]
The new update does not yet contain the option to set the IP manually.
Instead, I changed the way the adapter connects to the gateway.
It now tries all of the advertised addresses one by one unit it can connect to the gateway.
If the problem in your case was the mDNS resolution, this should solve your issue.

**Comment by tim-hellhake** [comment]
The next update should contain an option in the settings to add gateway by IP/hostname.

**Comment by davvore33** [comment]
I tried to insert the ip manually, it's perfect, thanks!
